# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: kubectl-aws-sso-login

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-aws-sso-login
    main: .
    binary: kubectl-aws-sso-login
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/rnakamine/kubectl-aws-sso-login/pkg/version.Version={{ .Version }}
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto

changelog:
  disable: true
